name: 02 - Workflow Events

on: 
    #push:
    pull_request:
    #schedule:
     #   - cron: "* * * * *"
    #workflow_dispatch:

jobs:
    echo-second:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
               echo "I have been triggered by : ${{ github.event_name }} using temp branch"