name: 04-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        # 0. checkout the code
        # 1.　Install dep of react application
        # 2. Execute automated tests
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls  
        