name: 05 - 2 - Event Filters and Activity Types

on: 
    pull_request:
        types: [closed]
        branches:
            - main
            - 'releases/**'

jobs:
    filter-types-2-echo:
        runs-on: ubuntu-latest
        steps:
            - name: print message
              run: "Running whenever a PR is closed"
