name: 07 - Using Expressions

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
            


jobs:
    echo-expression:    
        runs-on: ubuntu-latest

        steps:
           - name: Print start-up data
             if: inputs.debug == true

             run: |
              echo "Triggered by: <${{github.event_name}}>"
              echo "Branch: <${{github.ref}}>"
              echo "Commit SHA: <${{github.sha}}>"
              echo "Runner OS: <${{github.actor}}>"
               

           - name: Print when triggered from main
             if: github.event_name == 'push' && inputs.debug == true

             run: |
              echo "I was triggered from main"

           - name: Print hello
             run: |
              echo "Hello, world"   