name: 08 - using variables

on: 
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: "I AM WORKFLOW VARIABLE"    
    OVERWRITTEN: "I AM OVERWRITTEN VARIABLE at workflow level"
   
        
jobs:
    echo-variables:
        runs-on: ubuntu-latest

        env:
            JOB_VARIABLE: "I am job variable"
            OVERWRITTEN: "I am overwritten variable at job level"
        steps: 
            - name: print variable data
              env:
                STEP_VARIABLE: "I am step1 variable" 
                OVERWRITTEN: "I am overwritten variable at step level" 
              run: |
                echo "workflow variable: ${{env.WORKFLOW_VAR}}"
                echo "job variable: ${{env.JOB_VARIABLE}}"    
                echo "step variable: ${{env.STEP_VARIABLE}}"   
                echo "overwritten variable: ${{env.OVERWRITTEN}}"  
                echo "print overwritten data $STEP_VARIABLE"    


    echo-repository-variable:
        runs-on: ubuntu-latest
        steps:             
            - name: print repository variables
              run: |
                  echo "Repository variable: ${{vars.MY_REPOSITORY_VAR}}"
                  echo "Repository overwritten variable: ${{vars.OVERWRITTEN_VAR_EX}}"   
                  
           
           
    echo-prod-environment-variable:
        runs-on: ubuntu-latest
        environment: Prod
        steps:                
            - name: print prod environment variables 
              run: |
                echo "Repository variable: ${{vars.TARGET_ENV}}"
                echo "Repository overwritten variable: ${{vars.OVERWRITTEN_VAR_EX}}"  

    echo-stg-environment-variable:
        runs-on: ubuntu-latest
        environment: Staging
        steps:                
            - name: print staging environment variables 
              run: |
                echo "Environment variable: ${{vars.TARGET_ENV}}"
                echo "Environment overwritten variable: ${{vars.OVERWRITTEN_VAR_EX}}"
                echo "Undefined variable: ${{vars.Random || 'There no random variable'}}"                   
                      

            #- name: test overwritten data
             # run: |
              #  echo "print overwritten data $STEP_VARIABLE"      